apiVersion: apps/v1
kind: Deployment
metadata:
  name: subrecommend
  namespace: ondal
  labels:
    app: subrecommend
spec:
  selector:
    matchLabels:
      app: subrecommend
  replicas: 1
  template:
    metadata:
      name: subrecommend
      labels:
        app: subrecommend
    spec:
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: subrecommend
          image: docker.io/hiondal/subrecommend:2.0.0
          imagePullPolicy: Always
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APPLICATION_NAME
              value: subrecommend
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: subride
          - configMapRef:
              name: subrecommend
          - secretRef:
              name: subride
          ports:
            - name: container-port
              containerPort: 18080
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: subrecommend
  namespace: ondal
data:
  SPRING_APPLICATION_NAME: subrecommend-service
  SERVER_PORT: "18080"
  DB_URL: jdbc:mysql://mysql-primary-headless:3306/subrecommend?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
---
apiVersion: v1
kind: Service
metadata:
  name: subrecommend
  namespace: ondal
spec:
  type: ClusterIP
  selector:
    app: subrecommend
  ports:
    - name: subrecommend
      port: 18080
      targetPort: 18080
---
apiVersion: v1
kind: Service
metadata:
  name: subrecommend-headless
  namespace: ondal
spec:
  clusterIP: None
  selector:
    app: subrecommend
  ports:
    - name: subrecommend
      port: 18080
      targetPort: 18080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subrecommend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: subrecommend.msa.edutdc.com
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: subrecommend
                port: 
                  number: 18080